name: Rust + Python CI

on:
    push:
        branches: [ dev, main ]
    pull_request:
        branches: [ main ]

jobs:
    test:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                python-version: [3.8, 3.9, 3.10, 3.11]
        steps:
            - uses: actions/checkout@v3

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                  python-version: ${{ matrix.python-version }}

            - name: Install Rust
              uses: dtolnay/rust-toolchain@stable

            - name: Install maturin
              run: pip install maturin numpy

            - name: Build Python extension (dev mode)
              run: maturin develop

            - name: Run Python tests
              run: pytest tests/

            - name: Run Rust tests
              run: cargo test
