name: Rust + Python CI

on:
    push:
        branches: [ dev, main ]
    pull_request:
        branches: [ main ]

jobs:
    test:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                python-version: [ "3.8", "3.9", "3.10", "3.11" ]
        steps:
            - uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                python-version: ${{ matrix.python-version }}

            - name: Install uv
              run: pip install uv

            - name: Create virtual environment
              run: uv venv .venv

            - name: Install Rust
              uses: dtolnay/rust-toolchain@stable

            - name: Activate environment and install tools
              run: |
                source .venv/bin/activate
                pip install maturin numpy pytest

            - name: Develop install using maturin
              run: |
                source .venv/bin/activate
                maturin develop

            - name: Run Python tests
              run: |
                source .venv/bin/activate
                pytest tests/

            - name: Run Rust tests
              run: cargo test
