name: Rust + Python CI

on:
    push:
        branches: [ dev, main ]
    pull_request:
        branches: [ main ]

jobs:
    test:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                python-version:
                    - "3.8"
                    - "3.9"
                    - "3.10"
                    - "3.11"
                    - "3.12"
        steps:
            - uses: actions/checkout@v4

            - name: Install uv
              uses: astral-sh/setup-uv@v5

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                python-version-file: ${{ matrix.python-version }}

            - name: Install Rust
              uses: dtolnay/rust-toolchain@stable

            - name: Set up venv and install dependencies
              run: |
                uv venv --upgrade-deps .venv
                echo "VIRTUAL_ENV=$PWD/.venv" >> $GITHUB_ENV
                echo "$PWD/.venv/bin" >> $GITHUB_PATH
                uv pip install maturin numpy pytest

            - name: Build and test with maturin + uv
              run: |
                uv run -- maturin develop
                uv run -- pytest tests

            - name: Run Rust tests
              run: cargo test
