name: Rust + Python CI

on:
    push:
        branches: [ dev, main ]
    pull_request:
        branches: [ main ]

jobs:
    test:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                python-version: [ "3.8", "3.9", "3.10", "3.11" ]
        steps:
            - uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                python-version: ${{ matrix.python-version }}

            - name: Install uv
              run: pip install uv

            - name: Install Rust
              uses: dtolnay/rust-toolchain@stable

            - name: Build and test with maturin
              run: |
                uv venv .venv
                echo "VIRTUAL_ENV=$PWD/.venv" >> $GITHUB_ENV
                echo "$PWD/.venv/bin" >> $GITHUB_PATH
                .venv/bin/pip install maturin numpy pytest
                maturin develop
                pytest tests/

            - name: Run Rust tests
              run: cargo test
