name: Rust + Python CI

on:
    push:
        branches: [ dev, main ]
    pull_request:
        branches: [ main ]

jobs:
    test:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                python-version:
                    - "3.8"
                    - "3.9"
                    - "3.10"
                    - "3.11"
                    - "3.12"
        steps:
            - uses: actions/checkout@v5

            - name: Install uv
              uses: astral-sh/setup-uv@v7

            - name: Install Rust
              uses: dtolnay/rust-toolchain@stable

            - name: Set up Python and install dependencies
              run: |
                uv python install ${{ matrix.python-version }}
                uv venv --python ${{ matrix.python-version }}
                uv pip install maturin numpy pytest

            - name: Build and test with maturin + uv
              run: |
                source .venv/bin/activate
                cargo clean
                maturin develop --release
                pytest tests

            - name: Run Rust tests
              run: cargo test
